- name: Docker configure in EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: updating the New EC2 Machine
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
      become: true

    - name: Check if any containers are running
      shell: docker ps -q
      register: running_containers
      ignore_errors: true

    - name: Stopping and removing running containers if any
      shell: docker rm -f $(docker ps -a -q)
      when: running_containers.stdout | length > 0
    
    - name: Check if any images exist
      shell: docker images -q
      register: existing_images
      ignore_errors: true
    
    - name: Cleaning up images if any exist
      shell: docker rmi -f $(docker images -a -q)
      when: existing_images.stdout | length > 0

    - name: Pull the Docker Image
      command: docker pull edisonthomas003/insureme_project123:latest

    - name: Deploy the Docker Image and Run as Container
      command: docker run -itd -p 8084:8083 edisonthomas003/insureme_project123:latest
